### ISSUE TITLE
Definitions of route-leak and hijack are weak / confusing

### ISSUE THREAD

**Issue by dougm-nist** [NLnetLabs/rpki-faq#4]
We spent a fair amount of time trying to get the community to agree on the definition of a route leak and it isn't what is here.   Definitions based upon the motivations of the offender are always problematic (and naive).

Cite: https://tools.ietf.org/html/rfc7908 - 

A route leak is a propagation of routing announcement(s) beyond their intended scope.  That is an announcement from an Autonomous System (AS) of a learned BGP route to another AS is in violation of the intended policies of the receiver, the sender, and/or one of the ASes along the preceding AS path. 

A route-hijack is the unauthorized origination of a route. 

Not that in either case, the cause may be accidental or malicious and in either case, the result can be path detours, redirection, or denial of services.

dougm

**Comment by AlexanderBand** [comment]
I rewrote the answer based on your suggestion. Thanks!
