### ISSUE TITLE
Add a Q on RRDP

### ISSUE THREAD

**Issue by dougm-nist** [NLnetLabs/rpki-faq#5]
We really need to encourage the RIRs and publication point implementations to get to RRDP, so it would be good to make people aware of this.

**Comment by job** [comment]
Agreed!

**Comment by AlexanderBand** [comment]
How about:

**Q:** Why do I need rsync on my system to use a validator?
**A:** In the original standards, rsync was defined as the main means of distribution of RPKI data. While it has served the system well in the early years, rsync has several downsides:

1. When RPKI relying party software is used on a client system, it has a dependency on rsync. Different versions and different supported options, such as `--contimeout`, cause unpredictable results. Furthermore, calling rsync is inefficient. It's an additional process and the output can only be verified by scanning the disk.
2. Scaling becomes more and more problematic as the global RPKI data set grows and more operators download and validate data, as with rsync the server in involved in processing the differences.

To overcome these limitations the RRDP protocol was developed and standardised in [RFC 8182](https://tools.ietf.org/html/rfc8182), which relies on HTTPS. RRDP was specifically designed for scaling and allows CDNs to participate in serving the RPKI data set globally, at scale. In addition, HTTPS is well supported in programming languages so development of relying party software becomes easier and more robust.

Currently, RRDP is implemented on the server side by the RIPE NCC and APNIC. It is [considered as a work item](https://www.arin.net/participate/acsp/suggestions/2018-14.html) for 2019 by ARIN. Most RPKI Validator implementations either already have RRDP support, or have it on the short term roadmap.
